### ISSUE TITLE
Abaqus 2020 and up

### ISSUE THREAD

**Issue by AJJLagerweij** [franaudo/abaqus-ubuntu#1]
Dear Franaudo,

Thanks for the very useful outline of steps. Today I installed Abaqus 2022 on Ubuntu 20.04 and without your guide I would not have been able to do it.

Sadly, there are some major differences in folder structure since 2020. There is no more `/usr/DessaultSystemes/` folder and nothing gets installed into `/opt/`. I've figured out the new location of everything and updated the guide accordingly. You can find that [here](https://github.com/AJJLagerweij/abaqus-ubuntu).

In the end, there is however a single issue that I have remaining, the font size changes. I can't seem to get that working. Do you have any idea what I'm doing wrong there?

Kind Regards,
Bram

**Comment by franaudo** [comment]
Hi @AJJLagerweij ,

thanks for your feedback. I am happy that you found this guide useful! Maybe the best way to incorporate your changes is to create a pull request to this repo, so we keep it up-to-date.

Regarding the font size, unfortunately I haven't tried to install the latest Abaqus on linux yet, so I am not sure I can help you.
Maybe if you describe the error we can find a solution.

Ciao,
FR

**Comment by AJJLagerweij** [comment]
This is exiting, my first ever pull request. <3

**Comment by franaudo** [comment]
sorry, I still didn't have time to go through it. I will do ASAP. Thanks again for your contribution!

**Comment by jcappola** [comment]
Hi all,

I just followed the installation steps from @AJJLagerweij PR and noticed that in the step "Make abaqus command available from any directory" there is a additional (`) character at the end of the command that should be removed. Other than that easy fix, everything up to "Shortcuts" works great (didn't need to do anything past that) and I have ABAQUS 2022 running on my Linux workstation.

On a side note, have either of you ever managed to get the features from SMApy to work? Commands like

` abaqus licensing -ru `

return for me this error:
```
Traceback (most recent call last):
File "SMAPylModules/SMAPylDriverPy.m/src/licensing.py", line 555, in <module>
File "SMAPylModules/SMAPylDriverPy.m/src/application.py", line 151, in run
File "SMAPylModules/SMAPylDriverPy.m/src/licensing.py", line 153, in execute
File "SMAPylModules/SMAPylDriverPy.m/src/licensing.py", line 226, in runCurrentUsageApp
File "SMAPyrModules/SMAPyrUtiPy.m/src/uti.py", line 37, in spawnAndWait
File "SMAPyrModules/SMAPyrUtiPy.m/src/utiSpawn.py", line 93, in spawnAndWait
File "SMAPyrModules/SMAPyrUtiPy.m/src/utiSpawnImpl.py", line 643, in spawnAndWait
File "SMAPyrModules/SMAPyrUtiPy.m/src/utiSpawnImpl.py", line 477, in __init__
File "SMAPyrModules/SMAPyrUtiPy.m/src/utiSpawnImpl.py", line 438, in popenWrap
File "/usr/SIMULIA/EstProducts/2022/linux_a64/tools/SMApy/python2.7/lib/python2.7/subprocess.py", line 394, in __init__
errread, errwrite)
File "/usr/SIMULIA/EstProducts/2022/linux_a64/tools/SMApy/python2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
```

**Comment by AJJLagerweij** [comment]
Thanks for noticing the error. 

Regarding the `abaqus licensing -ru`, I run into the same issue as you do. I didn't catch that before, as I didn't need it. I have no cue what the issue exactly is, nor how to solve it. Let's hope someone else does.

**Comment by franaudo** [comment]
@AJJLagerweij  thanks again for your pull request.
@jcappola sorry, I haven't tested it and I have no longer ubuntu on my machine.

**Comment by jcappola** [comment]
Hi guys (and everyone who finds this in the future),

It is that time of year again. I've gone through the installation of ABAQUS 2023 on Ubuntu 22.04.3 LTS using the updates proposed by AJJLagerweij. Everything worked out just about the same except "2022" is now "2023" everywhere. The modification of the custom_v6.env file to add in the FlexNET required adding in the two lines:

> license_server_type=FLEXNET
> abaquslm_license_file="<port>@<your_domain>"

since the file now(?) has some strange python-ic redirect to a licensing.env file which I commented out.

As for the bug where "abaqus licensing -ru" gives a Python traceback error instead of license usage information, you can simply run

> sudo apt install lsb

and it will work. See (https://stackoverflow.com/questions/61405706/coudnt-find-location-of-python-module).

**Comment by franaudo** [comment]
Amazing! Thanks a lot :)
